<?php

declare(strict_types=1);

namespace Modules\Shared\Console;

use Illuminate\Console\Command;
use Modules\Shared\Exceptions\ErrorCode;
use Modules\Shared\Support\OpenApiGenerator;

/**
 * Emits `docs/api/types.ts` from the same enums the API serialises (ADR 0038 §3).
 *
 * **ENUMS AND THE ENVELOPE, NOT A CLIENT SDK.** The master command says to generate TypeScript
 * where useful but not to overwrite frontend architecture blindly, and the line between the two is
 * exactly here: the *vocabulary* is the backend's to own, and how a client fetches is not.
 *
 * A generated SDK would arrive with an opinion about HTTP clients, error handling, retries and
 * state management — four decisions belonging to two Angular applications and a Flutter one that
 * have already made them. It would be regenerated over, argued with, and eventually deleted.
 *
 * A file of enums and envelope types is different: it is the part a frontend developer would
 * otherwise **retype by hand from prose**, getting one value wrong and finding out in production.
 * One source of truth for enums, which is what the master command actually asks for.
 */
final class GenerateTypesCommand extends Command
{
    protected $signature = 'lguids:types {--check : Fail if the committed file is stale}';

    protected $description = 'Generate TypeScript enums and envelope types from the backend enums';

    public function handle(OpenApiGenerator $generator): int
    {
        $path = base_path('docs/api/types.ts');
        $contents = $this->render($generator);

        if ($this->option('check')) {
            $committed = is_file($path) ? (string) file_get_contents($path) : '';

            if ($committed === $contents) {
                $this->info('The committed TypeScript contract is current.');

                return self::SUCCESS;
            }

            $this->error('docs/api/types.ts is stale. Run: php artisan lguids:types');

            return self::FAILURE;
        }

        file_put_contents($path, $contents);
        $this->info('Wrote '.$path);

        return self::SUCCESS;
    }

    private function render(OpenApiGenerator $generator): string
    {
        $lines = [
            '// Generated by `php artisan lguids:types`. Do not edit.',
            '//',
            '// The vocabulary the backend serialises, and the envelope every response uses.',
            '// Deliberately NOT a client SDK: how a client fetches is the frontend\'s decision,',
            '// and a generated one would arrive with opinions about HTTP, retries and state that',
            '// three existing applications have already made (ADR 0038 §3).',
            '//',
            '// TREAT THESE AS OPEN. A new enum value is an additive change (CHANGELOG_API.md), so',
            '// a client with an exhaustive switch will fall through the day one is added. Handle',
            '// the unknown case.',
            '',
            'export interface ApiMeta {',
            '  request_id: string;',
            '  // Present on every collection response, absent on a single resource.',
            '  // These five keys are what the wire carries; `has_more` was previously served but not published.',
            '  pagination?: { page: number; per_page: number; total: number; total_pages: number; has_more: boolean };',
            '}',
            '',
            'export interface ApiResponse<T> {',
            '  data: T;',
            '  meta: ApiMeta;',
            '}',
            '',
            '/** Branch on `code`. `message` is written for operators and may be reworded. */',
            'export interface ApiError {',
            '  error: {',
            '    code: ApiErrorCode;',
            '    message: string;',
            '    details?: Record<string, unknown>;',
            '    request_id?: string;',
            '  };',
            '}',
            '',
            'export type ApiErrorCode =',
        ];

        foreach (ErrorCode::cases() as $index => $code) {
            $lines[] = sprintf(
                '  %s %s%s',
                $index === 0 ? ' ' : '|',
                // The backing value, not the case name — see OpenApiGenerator::schemas().
                // A client branching on the published union must match what the wire carries.
                "'".$code->value."'",
                $index === count(ErrorCode::cases()) - 1 ? ';' : '',
            );
        }

        $lines[] = '';

        foreach ($generator->domainEnums() as $name => $class) {
            $values = array_map(
                static fn (\BackedEnum $case): string => "  '".$case->value."'",
                $class::cases(),
            );

            $lines[] = sprintf('export type %s =', $name);
            $lines[] = implode("\n", array_map(
                static fn (string $value, int $i): string => ($i === 0 ? ' ' : '|').$value,
                $values,
                array_keys($values),
            )).';';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }
}
