<?php

declare(strict_types=1);

namespace Modules\Shared\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Route;

/**
 * Writes the published API surface to `docs/api/routes.published.json`.
 *
 * The file exists so that removing a route is a line in a diff (TAB 18). This command only
 * regenerates it; `PublishedRoutesAreStableTest` is what refuses a silent removal.
 *
 * In `Shared` rather than `Audit`, unlike the preflight: it asks the framework's own router and
 * nothing else, so it depends on no module.
 */
final class PublishedRoutesCommand extends Command
{
    protected $signature = 'lguids:routes {--write : Rewrite the snapshot rather than printing it}';

    protected $description = 'Show or rewrite the published /api/v1 route snapshot';

    public function handle(): int
    {
        $routes = [];

        foreach (Route::getRoutes() as $route) {
            if (! str_starts_with($route->uri(), 'api/v1')) {
                continue;
            }

            foreach ($route->methods() as $method) {
                if ($method !== 'HEAD') {
                    $routes[] = $method.' /'.$route->uri();
                }
            }
        }

        $routes = array_values(array_unique($routes));
        sort($routes);

        $payload = json_encode([
            '$comment' => 'The published /api/v1 surface. Generated by `php artisan lguids:routes --write`. '
                .'Removing a line here is what records CONSOLE-BEFORE-API for a release; adding one records '
                .'API-BEFORE-CONSOLE. Never edit by hand to make a test pass.',
            'count' => count($routes),
            'routes' => $routes,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL;

        if (! $this->option('write')) {
            $this->line($payload);

            return self::SUCCESS;
        }

        file_put_contents(base_path('docs/api/routes.published.json'), $payload);
        $this->info(count($routes).' routes written to docs/api/routes.published.json');

        return self::SUCCESS;
    }
}
