// Generated by `php artisan lguids:types`. Do not edit.
//
// The vocabulary the backend serialises, and the envelope every response uses.
// Deliberately NOT a client SDK: how a client fetches is the frontend's decision,
// and a generated one would arrive with opinions about HTTP, retries and state that
// three existing applications have already made (ADR 0038 §3).
//
// TREAT THESE AS OPEN. A new enum value is an additive change (CHANGELOG_API.md), so
// a client with an exhaustive switch will fall through the day one is added. Handle
// the unknown case.

export interface ApiMeta {
  request_id: string;
  pagination?: { page: number; per_page: number; total: number; total_pages: number };
}

export interface ApiResponse<T> {
  data: T;
  meta: ApiMeta;
}

/** Branch on `code`. `message` is written for operators and may be reworded. */
export interface ApiError {
  error: {
    code: ApiErrorCode;
    message: string;
    details?: Record<string, unknown>;
    request_id?: string;
  };
}

export type ApiErrorCode =
    'BadRequest'
  | 'Unauthenticated'
  | 'Forbidden'
  | 'NotFound'
  | 'MethodNotAllowed'
  | 'Conflict'
  | 'InvalidStateTransition'
  | 'ValidationFailed'
  | 'RateLimited'
  | 'PayloadTooLarge'
  | 'UnsupportedMediaType'
  | 'ServerError'
  | 'ServiceUnavailable';

export type AccessControlPermission =
   'kyc.review'
|  'kyc.approve'
|  'resident.view'
|  'resident.manage'
|  'resident.verify'
|  'resident.merge'
|  'resident.link_review'
|  'household.manage'
|  'request.view'
|  'request.view-sensitive'
|  'request.create'
|  'request.intake'
|  'request.assess'
|  'request.endorse'
|  'request.approve'
|  'request.reject'
|  'request.schedule'
|  'request.release'
|  'request.close'
|  'request.assign'
|  'vulnerability.view'
|  'vulnerability.manage'
|  'vulnerability.view_protected'
|  'credential.manage'
|  'enrollment.view'
|  'enrollment.manage'
|  'document.manage'
|  'document.verify'
|  'document.view.sensitive'
|  'document.share'
|  'referral.view'
|  'referral.manage'
|  'referral.send'
|  'referral.disclose.protected'
|  'provider.manage'
|  'visit.view'
|  'visit.manage'
|  'case-note.view-protected'
|  'safeguarding.view'
|  'safeguarding.manage'
|  'task.view'
|  'task.manage'
|  'report.view'
|  'report.export.person-level'
|  'saved-view.share'
|  'newsfeed.manage'
|  'newsfeed.publish'
|  'newsfeed.moderate'
|  'operations.view'
|  'audit.view'
|  'privacy.manage'
|  'event.manage'
|  'event.publish'
|  'event.mark-attendance'
|  'event.export-registrants'
|  'program.view'
|  'program.manage'
|  'services.view_unpublished'
|  'services.manage'
|  'staff.manage'
|  'staff.view';

export type AccessControlRole =
   'resident'
|  'verifier'
|  'lgu_staff'
|  'lgu_admin'
|  'disbursing_officer'
|  'data_protection_officer'
|  'operations_engineer'
|  'security_officer';

export type AuditAuditRisk =
   'routine'
|  'high';

export type ContentModerationState =
   'visible'
|  'hidden'
|  'deleted'
|  'review-needed';

export type ContentPostStatus =
   'draft'
|  'scheduled'
|  'published'
|  'archived';

export type CredentialCredentialStatus =
   'issued'
|  'active'
|  'suspended'
|  'revoked'
|  'expired';

export type CredentialVerificationOutcome =
   'valid'
|  'expired'
|  'revoked'
|  'suspended'
|  'signature-invalid'
|  'replayed'
|  'malformed';

export type EventsAttendanceState =
   'not-checked-in'
|  'attended'
|  'no-show';

export type EventsEventStatus =
   'draft'
|  'published'
|  'cancelled'
|  'completed'
|  'archived';

export type EventsRegistrationAvailability =
   'not-open'
|  'open'
|  'closed'
|  'full'
|  'not-required';

export type EventsRegistrationStatus =
   'registered'
|  'waitlisted'
|  'cancelled';

export type FilesAcceptedMediaType =
   'image/jpeg'
|  'image/png'
|  'application/pdf';

export type FilesDocumentSource =
   'uploaded'
|  'scanned'
|  'encoded'
|  'external-verification';

export type FilesDocumentValidity =
   'valid'
|  'expiring-soon'
|  'expired'
|  'no-expiry'
|  'unknown';

export type FilesFileClassification =
   'public-reference'
|  'operational'
|  'personal'
|  'sensitive';

export type FilesMediaVariant =
   'thumbnail'
|  'web';

export type FilesMediaVisibility =
   'private'
|  'public';

export type FilesScanStatus =
   'pending'
|  'clean'
|  'infected'
|  'skipped';

export type FilesVerificationStatus =
   'pending'
|  'verified'
|  'rejected';

export type IdentityAccountStatus =
   'pending'
|  'active'
|  'suspended'
|  'deactivated';

export type IdentityAccountType =
   'citizen'
|  'staff';

export type IdentityVerificationPurpose =
   'sign-in'
|  'verify-email'
|  'verify-mobile';

export type ReportingReportCatalog =
   'case-summary'
|  'program-utilization'
|  'barangay-reach'
|  'referral-outcomes'
|  'release-manifest'
|  'event-registrants';

export type ResidentProfileCivilStatus =
   'single'
|  'married'
|  'widowed'
|  'separated'
|  'annulled'
|  'cohabiting';

export type ResidentProfileCorrectableField =
   'first_name'
|  'middle_name'
|  'last_name'
|  'suffix'
|  'birth_date'
|  'sex'
|  'civil_status'
|  'barangay_id'
|  'street_address'
|  'purok_or_sitio'
|  'mobile_number'
|  'email';

export type ResidentProfileCorrectionStatus =
   'pending'
|  'approved'
|  'rejected'
|  'withdrawn';

export type ResidentProfileKycStatus =
   'draft'
|  'submitted'
|  'screening'
|  'manual-review'
|  'needs-more-information'
|  'approved'
|  'rejected'
|  'withdrawn'
|  'expired';

export type ResidentProfileRelationshipType =
   'parent'
|  'child'
|  'guardian'
|  'ward'
|  'spouse'
|  'partner'
|  'sibling'
|  'dependent'
|  'provider'
|  'other';

export type ResidentProfileVerificationTier =
   'unverified'
|  'partially-verified'
|  'verified';

export type ServiceCatalogEligibilityFact =
   'age'
|  'barangay'
|  'sector'
|  'household-size'
|  'verification-tier'
|  'monthly-income';

export type ServiceCatalogEligibilityOutcome =
   'likely-eligible'
|  'likely-ineligible'
|  'needs-review';

export type ServiceCatalogPublicationStatus =
   'draft'
|  'published'
|  'retired';

export type ServiceCatalogServiceCategory =
   'dokumento'
|  'buwis'
|  'kalusugan'
|  'trabaho'
|  'ids'
|  'national';

export type TasksTaskPriority =
   'low'
|  'normal'
|  'high'
|  'urgent';

export type TasksTaskStatus =
   'open'
|  'done'
|  'cancelled';

export type TasksTaskType =
   'review-intake'
|  'verify-resident'
|  'request-requirements'
|  'complete-assessment'
|  'referral-follow-up'
|  'field-visit'
|  'recommendation'
|  'prepare-release'
|  'confirm-release'
|  'close-case'
|  'resolve-duplicate'
|  'general';

export type WelfareCasePriority =
   'low'
|  'normal'
|  'high'
|  'urgent';

export type WelfareCaseStatus =
   'draft'
|  'submitted'
|  'intake-review'
|  'returned'
|  'assessment'
|  'endorsed'
|  'approved'
|  'rejected'
|  'scheduled'
|  'released'
|  'completed'
|  'cancelled'
|  'expired';

export type WelfareCaseType =
   'assistance'
|  'medical'
|  'educational'
|  'relief'
|  'livelihood'
|  'protective'
|  'referral';

export type WelfareDisclosureBasis =
   'client-consent'
|  'statutory-mandate'
|  'vital-interest';

export type WelfareEnrollmentStatus =
   'active'
|  'suspended'
|  'exited';

export type WelfareIntakeSource =
   'walk-in'
|  'barangay-referral'
|  'citizen-web'
|  'citizen-mobile'
|  'legacy-import';

export type WelfareNoteSensitivity =
   'routine'
|  'protected';

export type WelfareObservationKind =
   'observed'
|  'client-said'
|  'third-party-said'
|  'worker-assessed';

export type WelfareRecommendation =
   'recommend-approve'
|  'recommend-deny'
|  'recommend-refer'
|  'insufficient-information';

export type WelfareReferralStatus =
   'draft'
|  'sent'
|  'acknowledged'
|  'in-progress'
|  'waiting-requirements'
|  'served'
|  'declined'
|  'closed';

export type WelfareReferralUrgency =
   'routine'
|  'priority'
|  'urgent';

export type WelfareReleaseStatus =
   'ready'
|  'released'
|  'completed'
|  'failed'
|  'deferred'
|  'cancelled';

export type WelfareRequirementApplicability =
   'undecided'
|  'applies'
|  'does-not-apply';

export type WelfareRequirementObligation =
   'required'
|  'optional'
|  'conditional';

export type WelfareSharedField =
   'birth-date'
|  'address'
|  'contact-number'
|  'household-composition'
|  'income'
|  'vulnerability-sectors'
|  'assistance-history';

export type WelfareVisitStatus =
   'scheduled'
|  'completed'
|  'not-found'
|  'refused'
|  'cancelled';
